version: '3.8'

services:
  hello-service:
    build: ./backend/helloService
    ports:
      - "3001:3001"
    env_file:
      - ./backend/helloService/.env
    networks:
      - mern-network

  profile-service:
    build: ./backend/profileService
    ports:
      - "3002:3002"
    env_file:
      - ./backend/profileService/.env
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - hello-service
      - profile-service
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
