version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network

  hello-service:
    build: ./backend/helloService
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - mern-network

  profile-service:
    build: ./backend/profileService
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - hello-service
      - profile-service
    networks:
      - mern-network

# 🔥 Define the network here
networks:
  mern-network:
    driver: bridge
