version: '3.8'

services:
  hello-service:
    build: ./backend/helloService
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - mern-network

  profile-service:
    build: ./backend/profileService
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - hello-service
      - profile-service
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
